import './dashboardLayout.css';
import SideBar from '@/components/SideBar/SideBar';

export const metadata = {
  title: 'Ai voice Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div className="dashboardBody">
      <div className="dashboardWrapper">
        <SideBar />
        <div className="dashboardContent">{children}</div>
      </div>
    </div>
  );
}
