import './dashboardLayout.css';
import SideBar from '@/components/SideBar/SideBar';

export const metadata = {
  title: 'Ai voice Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="dashboardBody">
          <SideBar />
          <div className="dashboardContent">{children}</div>
        </div>
      </body>
    </html>
  );
}
